# Generated by Django 2.1.1 on 2019-07-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cas_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
                ('access', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='client_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cas_client',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udev_auth.client_user'),
        ),
    ]
