# Generated by Django 2.1.1 on 2019-07-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cas_client',
            old_name='user_id',
            new_name='user',
        ),
    ]
