# Generated by Django 2.1.1 on 2019-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0003_auto_20190719_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='cas_client',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client_user',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
