# Generated by Django 2.1.1 on 2019-07-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0004_auto_20190719_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cas_client',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cas_client',
            name='url',
        ),
    ]
