# Generated by Django 2.1.1 on 2019-07-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0005_auto_20190719_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas_client',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
