# Generated by Django 2.1.1 on 2019-07-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0006_auto_20190719_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas_client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
