# Generated by Django 2.1.1 on 2019-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0007_auto_20190723_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas_client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client_list',
            name='img',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client_list',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client_user',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
