# Generated by Django 2.1.1 on 2019-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0008_auto_20190723_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_list',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
