# Generated by Django 2.1.1 on 2019-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0009_auto_20190723_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_list',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images'),
        ),
    ]
