# Generated by Django 2.1.1 on 2019-07-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0009_auto_20190723_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_list_del',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
