# Generated by Django 2.1.1 on 2019-07-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0010_client_list_del'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_list_del',
        ),
    ]
