# Generated by Django 2.1.1 on 2019-08-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0010_auto_20190801_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_list',
            name='callback',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
    ]
