# Generated by Django 2.1.1 on 2019-08-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udev_auth', '0011_client_list_callback'),
        ('udev_auth', '0011_delete_client_list_del'),
    ]

    operations = [
    ]
